const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.custom,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.custom.Acts.PushOutSolidAngle,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Custom: 0},
	{Pin: 0},
	{player: 0},
	{rockfire: 0},
	{Solid: 0},
	{shape: 0},
	{"3DCamera": 0},
	{Mouse: 0},
	{Keyboard: 0},
	{zAxis: 0},
	{speed: 0},
	{Bullet: 0},
	{"3DShape": 0},
	{health: 0},
	{MoveTo: 0},
	{enemy: 0},
	{spawn_enemy: 0},
	{temboklabirin: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Sprite3: 0},
	{Score: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{"3DShape2": 0},
	{Audio: 0},
	{Sprite: 0},
	{HealthBar: 0},
	{InitialWidth: 0},
	{HealthBorder: 0},
	{Sprite2: 0},
	{Button: 0},
	{Sprite6: 0},
	{Touch: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{atas: 0},
	{bawah: 0},
	{kiri: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{PlayerHeight: 0},
	{PlayerSpeed: 0},
	{MouseSpeed: 0},
	{Life: 0},
	{LifeMax: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	rockfire: class extends self.ITiledBackgroundInstance {},
	shape: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	enemy: class extends self.I3DShapeInstance {},
	spawn_enemy: class extends self.ISpriteInstance {},
	temboklabirin: class extends self.I3DShapeInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	_3DShape2: class extends self.I3DShapeInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	HealthBorder: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	atas: class extends self.ISpriteInstance {},
	bawah: class extends self.ISpriteInstance {},
	kiri: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {}
}